all:
	g++ lista_linear_sequencial.cpp --std=c++11 -g -o lista_linear_sequencial
	g++ lista_linear_ordenada.cpp --std=c++11 -g -o lista_linear_ordenada
	g++ lista_benchmark.cpp --std=c++11 -g -o lista_benchmark
	g++ lista_ligada.cpp --std=c++11 -g -o lista_ligada
	g++ banco_de_dados.cpp --std=c++11 -g -o banco_de_dados

clean:
	rm lista_linear_sequencial lista_linear_ordenada *~ -rf
	rm lista_benchmark lista_ligada *~ -rf
	rm banco_de_dados *~ -rf
